site_name: LorefulLoot
site_description: A Lore and Salvage Expansion Mod for StarMade
theme:
  name: readthedocs

nav:
  - Home: index.md
  - Generation JSON Configuration: configuration.md
  - Loot Pools & Weights: loot_pools.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - fenced_code
